# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Nighly ECS example validator
on:
  # schedule:
  #   - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:
  push:

jobs:
  single-cluster:
    strategy:
      matrix:
        name:
          - Consul ECS on Fargate
          - Consul ECS on EC2
          - Admin partitions
        include:
          - name: Consul ECS on Fargate
            region: us-east-1
            working-directory: ./examples/dev-server-fargate
            variables: '{\"lb_ingress_ip\": \"eval curl -s ifconfig.me\", \"name\": \"ecs-ywxt\"}'

          - name: Consul ECS on EC2
            region: us-east-2
            working-directory: ./examples/dev-server-ec2
            variables: '{\"lb_ingress_ip\": \"eval curl -s ifconfig.me\", \"name\": \"ecs-rtya\"}'
          
          - name: Admin partitions
            region: us-west-2
            working-directory: ./examples/admin-partitions/terraform
      fail-fast: false
    uses: ./.github/workflows/reusable-ecs-example-validator.yml
    with:
      name: ${{ matrix.name }}
      region: ${{ matrix.region }}
      working-directory: ${{ matrix.working-directory }}
      variables: ${{ matrix.variables }}
    secrets: inherit
  multi-cluster:
      strategy:
        matrix:
          name:
            - Mesh gateways
            - Cluster peering
          include:
            
            - name: Mesh gateways
              region: us-east-1
              working-directory: ./examples/mesh-gateways
              variables: '{\"lb_ingress_ip\": \"eval curl -s ifconfig.me\", \"name\": \"ecs-oprb\"}'
  
            - name: Cluster peering
              region: us-east-2
              working-directory: ./examples/cluster-peering
              variables: '{\"lb_ingress_ip\": \"eval curl -s ifconfig.me\", \"name\": \"ecs-oerc\"}'
        fail-fast: false
      uses: ./.github/workflows/reusable-ecs-example-validator.yml
      with:
        name: ${{ matrix.name }}
        region: ${{ matrix.region }}
        working-directory: ${{ matrix.working-directory }}
        variables: ${{ matrix.variables }}
      secrets: inherit