# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: terraform-ci
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - 'release/**'

permissions: {}
jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Lint workflow
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint:latest
        with:
          # we need to ignore the SC2086 rule to pass unescaped $VARS to the terraform commands
          args: -ignore SC2086
  get-go-version:
    uses: ./.github/workflows/reusable-get-go-version.yml
  go-fmt-and-lint-acceptance:
    needs:
    - get-go-version
    uses: ./.github/workflows/reusable-go-fmt-and-lint.yml
    with:
      go-version: ${{ needs.get-go-version.outputs.go-version }}
  terraform-fmt:
    needs:
    - action-lint
    uses: ./.github/workflows/reusable-terraform-fmt.yml
  acceptance-fargate:
    needs:
      - get-go-version
      - terraform-fmt
      - go-fmt-and-lint-acceptance
    strategy:
      # We have a limit of 6 HCP Consul clusters.
      # The following controls whether to enable HCP when testing release branches.
      # HCP is always disabled for tests on PRs.
      matrix:
        name:
          - acceptance-1.17-FARGATE-HCP
          - acceptance-1.17-FARGATE
        include:
          - name: acceptance-1.17-FARGATE-HCP
            enable-hcp: true
            launch-type: FARGATE

          - name: acceptance-1.17-FARGATE
            enable-hcp: false
            launch-type: FARGATE
      fail-fast: false
    uses: ./.github/workflows/reusable-ecs-acceptance.yml
    with:
      go-version: ${{ needs.get-go-version.outputs.go-version }}
      name: ${{ matrix.name }}
      launch-type: ${{ matrix.launch-type }}
      enable-hcp: ${{ matrix.enable-hcp }}
    secrets: inherit
  acceptance-ec2:
    needs:
      - get-go-version
      - acceptance-fargate
    strategy:
      # We have a limit of 6 HCP Consul clusters.
      # The following controls whether to enable HCP when testing release branches.
      # HCP is always disabled for tests on PRs.
      matrix:
        name:
          - acceptance-1.17-EC2-HCP
          - acceptance-1.17-EC2
        include:
          - name: acceptance-1.17-EC2-HCP
            enable-hcp: true
            launch-type: EC2

          - name: acceptance-1.17-EC2
            enable-hcp: false
            launch-type: EC2
      fail-fast: false
    uses: ./.github/workflows/reusable-ecs-acceptance.yml
    with:
      go-version: ${{ needs.get-go-version.outputs.go-version }}
      name: ${{ matrix.name }}
      launch-type: ${{ matrix.launch-type }}
      enable-hcp: ${{ matrix.enable-hcp }}
    secrets: inherit