# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: terraform-ci
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - 'release/**'
env:
  CONSUL_LICENSE: ${{ secrets.CONSUL_LICENSE }}
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
permissions: {}
jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Lint workflow
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint:latest
        with:
          # we need to ignore the SC2086 rule to pass unescaped $VARS to the terraform commands
          args: -ignore SC2086
  get-go-version:
    runs-on: ubuntu-latest
    needs:
      - action-lint
    defaults:
      run:
        working-directory: ./test/acceptance
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Determine Go version
        id: get-go-version
        # We use .go-version as our source of truth for current Go
        # version, because "goenv" can react to it automatically.
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> "$GITHUB_OUTPUT"
  go-fmt-and-lint-acceptance:
    runs-on: ubuntu-latest
    needs:
      - get-go-version
    defaults:
      run:
        working-directory: ./test/acceptance
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Setup Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
          cache-dependency-path: ./test/acceptance/go.sum
      - name: Go CI lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3.4.0
        with:
          args: "--verbose --enable gofmt"
          only-new-issues: false
          skip-pkg-cache: true
          skip-build-cache: true
          working-directory: ./test/acceptance
      - name: Lint Consul retry
        run: |
          go install github.com/hashicorp/lint-consul-retry@v1.3.0
          lint-consul-retry
  terraform-fmt:
    runs-on: ubuntu-latest
    needs:
      - action-lint
    steps:
    - name: Checkout
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.2
    - name: Validate
      run: terraform fmt -check -recursive .
  acceptance_1_15:
    needs:
      - get-go-version
      - terraform-fmt
      - go-fmt-and-lint-acceptance
    strategy:
      fail-fast: false
      matrix:
        name:
          - acceptance-1.15-FARGATE-HCP
          - acceptance-1.15-EC2
        include:
          - name: acceptance-1.15-FARGATE-HCP
            consul-version: '1.15.9'
            enable-hcp: true
            launch-type: FARGATE

          - name: acceptance-1.15-EC2
            consul-version: '1.15.10'
            enable-hcp: false
            launch-type: EC2

    uses: ./.github/workflows/reusable-ecs-acceptance.yml
    with:
      go-version: ${{ needs.get-go-version.outputs.go-version }}
      name: ${{ matrix.name }}
      launch-type: ${{ matrix.launch-type }}
      enable-hcp: ${{ matrix.enable-hcp }}
      consul-version: ${{ matrix.consul-version }}
    secrets: inherit
  acceptance_1_14:
    needs:
      - get-go-version
      - acceptance_1_15
    strategy:
      fail-fast: false
      matrix:
        name:
          - acceptance-1.14-FARGATE-HCP
          - acceptance-1.14-EC2
        include:
          - name: acceptance-1.14-FARGATE-HCP
            consul-version: '1.14.11'
            enable-hcp: true
            launch-type: FARGATE

          - name: acceptance-1.14-EC2
            consul-version: '1.14.11'
            enable-hcp: false
            launch-type: EC2

    uses: ./.github/workflows/reusable-ecs-acceptance.yml
    with:
      go-version: ${{ needs.get-go-version.outputs.go-version }}
      name: ${{ matrix.name }}
      launch-type: ${{ matrix.launch-type }}
      enable-hcp: ${{ matrix.enable-hcp }}
      consul-version: ${{ matrix.consul-version }}
    secrets: inherit
  acceptance_1_13:
    needs:
      - get-go-version
      - acceptance_1_14
    strategy:
      fail-fast: false
      matrix:
        name:
          - acceptance-1.13-EC2-HCP
          - acceptance-1.13-FARGATE
        include:
          - name: acceptance-1.13-EC2-HCP
            consul-version: '1.13.9'
            enable-hcp: true
            launch-type: EC2

          - name: acceptance-1.13-FARGATE
            consul-version: '1.13.9'
            enable-hcp: false
            launch-type: FARGATE

    uses: ./.github/workflows/reusable-ecs-acceptance.yml
    with:
      go-version: ${{ needs.get-go-version.outputs.go-version }}
      name: ${{ matrix.name }}
      launch-type: ${{ matrix.launch-type }}
      enable-hcp: ${{ matrix.enable-hcp }}
      consul-version: ${{ matrix.consul-version }}
    secrets: inherit